GET http://localhost:3000/api/user/

###
POST http://localhost:3000/api/user
Content-Type: application/json

{
  "email": "miguel@gmail.com",
  "password": "miguel321"
}

###
GET http://localhost:3000/api/posts

###
PUT http://localhost:3000/api/posts/664002114291970455b9ebad
Content-Type: application/json

{
  "title": "Fazendo um PUT na postagem como teste da nova api",
  "description": "Mudei a postagem como um teste para a nova api"
}

###
POST http://localhost:3000/api/posts/663c03a6ebd5fca6f44e6658
Content-Type: application/json

{
  "title": "Postagem de teste",
  "description": "Postagem de teste para a nova api"
}


###

DELETE http://localhost:3000/api/logout/663c1db2c42b99c922295a73